// Package tsconstgen generates the TypeScript constants that the engine
// package shares with the Go code, with github.com/coder/guts.
//
// The output holds every exported constant and string type of package
// internal/result, and tebanare.ConfigFileNames. Do not edit
// packages/engine/src/generated/constants.ts; change the Go declarations
// and run make constants.
package tsconstgen

import (
	"fmt"
	"go/types"
	"slices"
	"strings"

	"github.com/coder/guts"
	"github.com/coder/guts/bindings"
	"github.com/coder/guts/config"
	"golang.org/x/tools/go/packages"

	tebanare "github.com/miyamo2/go-tebanare"
)

const (
	resultPkg   = "github.com/miyamo2/go-tebanare/internal/result"
	tebanarePkg = "github.com/miyamo2/go-tebanare"
)

const header = "// Code generated by dev/tsconstgen from internal/result and tebanare.ConfigFileNames. DO NOT EDIT.\n" +
	"// Run make constants to regenerate it.\n\n"

// Generate returns the content of packages/engine/src/generated/constants.ts.
func Generate() (string, error) {
	p, err := guts.NewGolangParser()
	if err != nil {
		return "", err
	}
	p.PreserveComments()
	if err := p.IncludeGenerate(resultPkg); err != nil {
		return "", err
	}
	ts, err := p.ToTypescript()
	if err != nil {
		return "", err
	}
	// EnumAsTypes turns a string type and its constants into a union of
	// the values.
	ts.ApplyMutations(config.EnumAsTypes, config.ExportTypes)

	names, err := configFileNames()
	if err != nil {
		return "", err
	}
	if err := ts.SetNode("ConfigFileNames", names); err != nil {
		return "", err
	}

	out, err := ts.SerializeInOrder(func(nodes map[string]bindings.Node) []bindings.Node {
		keys := make([]string, 0, len(nodes))
		for k, n := range nodes {
			// Structs stay in packages/engine/src/types.ts, which adapts
			// them for TypeScript callers.
			if _, ok := n.(*bindings.Interface); ok {
				continue
			}
			keys = append(keys, k)
		}
		slices.Sort(keys)
		out := make([]bindings.Node, 0, len(keys))
		for _, k := range keys {
			out = append(out, nodes[k])
		}
		return out
	})
	if err != nil {
		return "", err
	}
	body, ok := strings.CutPrefix(out, "// Code generated by 'guts'. DO NOT EDIT.\n\n")
	if !ok {
		return "", fmt.Errorf("unexpected guts header in %q", out[:min(len(out), 80)])
	}
	return header + strings.TrimRight(body, "\n") + "\n", nil
}

// configFileNames returns the declaration of ConfigFileNames. guts
// translates constants and types only, so this function reads the value
// from tebanare.ConfigFileNames and the comment from its declaration.
func configFileNames() (*bindings.VariableStatement, error) {
	pkgs, err := packages.Load(&packages.Config{
		Mode: packages.NeedName | packages.NeedTypes | packages.NeedSyntax | packages.NeedTypesInfo,
	}, tebanarePkg)
	if err != nil {
		return nil, err
	}
	if len(pkgs) != 1 || len(pkgs[0].Errors) > 0 {
		return nil, fmt.Errorf("load %s: %v", tebanarePkg, packages.PrintErrors(pkgs))
	}
	obj, ok := pkgs[0].Types.Scope().Lookup("ConfigFileNames").(*types.Var)
	if !ok {
		return nil, fmt.Errorf("%s.ConfigFileNames is not a variable", tebanarePkg)
	}

	str := bindings.KeywordString
	elems := make([]bindings.ExpressionType, 0, len(tebanare.ConfigFileNames))
	for _, n := range tebanare.ConfigFileNames {
		elems = append(elems, &bindings.LiteralType{Value: n})
	}
	stmt := &bindings.VariableStatement{
		Modifiers: []bindings.Modifier{bindings.ModifierExport},
		Declarations: &bindings.VariableDeclarationList{
			Declarations: []*bindings.VariableDeclaration{{
				Name: bindings.Identifier{Name: "ConfigFileNames"},
				Type: bindings.OperatorNode(bindings.KeywordReadonly,
					&bindings.ArrayType{Node: &str}),
				Initializer: &bindings.ArrayLiteralType{Elements: elems},
			}},
			Flags: bindings.NodeFlagsConstant,
		},
		Source: bindings.Source{File: "configfile.go"},
	}
	stmt.AppendComments(guts.CommentForObject(obj, pkgs[0]))
	return stmt, nil
}
