// Code generated by dev/gogen from schema/gotebanare.schema.json; DO NOT EDIT.

package presets

// GetterSettings holds the settings of the getter preset.
type GetterSettings struct {
	// Globs that limit the files this preset applies to, on top of
	// `files.include` and `files.exclude`.
	Paths []string `yaml:"paths"`

	// Globs of files this preset skips, on top of `files.exclude`.
	ExcludePaths []string `yaml:"exclude_paths"`

	// Hide the doc comment together with the function.
	IncludeDoc bool `yaml:"include_doc"`

	// The maximum number of fields in the returned chain: with 1, `u.name`
	// matches and `u.cfg.timeout` does not.
	MaxDepth *int `yaml:"max_depth"`
}

// newGetterSettings returns a GetterSettings that holds the defaults.
func newGetterSettings() *GetterSettings {
	return &GetterSettings{IncludeDoc: true}
}

// decodeGetterSettings reads m, a value that passed the schema. A null or
// missing value keeps the default.
func decodeGetterSettings(m map[string]any) *GetterSettings {
	s := newGetterSettings()
	if v := m["paths"]; v != nil {
		s.Paths = stringsValue(v)
	}
	if v := m["exclude_paths"]; v != nil {
		s.ExcludePaths = stringsValue(v)
	}
	if v := m["include_doc"]; v != nil {
		s.IncludeDoc = boolValue(v)
	}
	if v := m["max_depth"]; v != nil {
		n := intValue(v)
		s.MaxDepth = &n
	}
	return s
}

var getterSettingsSpec = settingsSpec{
	new:    func() any { return newGetterSettings() },
	decode: func(m map[string]any) any { return decodeGetterSettings(m) },
	infos: []SettingInfo{
		{Name: "paths", Type: "[]string", Default: "none", Description: "Globs that limit the files this preset applies to, on top of `files.include` and `files.exclude`."},
		{Name: "exclude_paths", Type: "[]string", Default: "none", Description: "Globs of files this preset skips, on top of `files.exclude`."},
		{Name: "include_doc", Type: "bool", Default: "true", Description: "Hide the doc comment together with the function."},
		{Name: "max_depth", Type: "int", Default: "unlimited", Description: "The maximum number of fields in the returned chain: with 1, `u.name` matches and `u.cfg.timeout` does not."},
	},
}

// IferrSettings holds the settings of the iferr preset.
type IferrSettings struct {
	// Globs that limit the files this preset applies to, on top of
	// `files.include` and `files.exclude`.
	Paths []string `yaml:"paths"`

	// Globs of files this preset skips, on top of `files.exclude`.
	ExcludePaths []string `yaml:"exclude_paths"`

	// Names of error variables, as globs matched against the whole name, where
	// `*` matches any run of characters and `?` matches one.
	Names []string `yaml:"names"`

	// Hide the statement even when a comment is on the hidden lines.
	AllowComments bool `yaml:"allow_comments"`

	// How to treat if statements with an init statement: `exclude` keeps them
	// visible; `fold-body` hides the lines from `return` to the closing brace
	// and keeps the header line visible.
	Init string `yaml:"init"`

	// Also hide a bare return.
	AllowBareReturn bool `yaml:"allow_bare_return"`

	// Allow function calls in the results before the error; function literals
	// and channel receives still do not match.
	AllowCallsInResults bool `yaml:"allow_calls_in_results"`
}

// newIferrSettings returns a IferrSettings that holds the defaults.
func newIferrSettings() *IferrSettings {
	return &IferrSettings{Names: []string{"err"}, Init: "exclude"}
}

// decodeIferrSettings reads m, a value that passed the schema. A null or
// missing value keeps the default.
func decodeIferrSettings(m map[string]any) *IferrSettings {
	s := newIferrSettings()
	if v := m["paths"]; v != nil {
		s.Paths = stringsValue(v)
	}
	if v := m["exclude_paths"]; v != nil {
		s.ExcludePaths = stringsValue(v)
	}
	if v := m["names"]; v != nil {
		s.Names = stringsValue(v)
	}
	if v := m["allow_comments"]; v != nil {
		s.AllowComments = boolValue(v)
	}
	if v := m["init"]; v != nil {
		s.Init = stringValue(v)
	}
	if v := m["allow_bare_return"]; v != nil {
		s.AllowBareReturn = boolValue(v)
	}
	if v := m["allow_calls_in_results"]; v != nil {
		s.AllowCallsInResults = boolValue(v)
	}
	return s
}

var iferrSettingsSpec = settingsSpec{
	new:    func() any { return newIferrSettings() },
	decode: func(m map[string]any) any { return decodeIferrSettings(m) },
	infos: []SettingInfo{
		{Name: "paths", Type: "[]string", Default: "none", Description: "Globs that limit the files this preset applies to, on top of `files.include` and `files.exclude`."},
		{Name: "exclude_paths", Type: "[]string", Default: "none", Description: "Globs of files this preset skips, on top of `files.exclude`."},
		{Name: "names", Type: "[]string", Default: "[err]", Description: "Names of error variables, as globs matched against the whole name, where `*` matches any run of characters and `?` matches one."},
		{Name: "allow_comments", Type: "bool", Default: "false", Description: "Hide the statement even when a comment is on the hidden lines."},
		{Name: "init", Type: "string", Default: "exclude", Description: "How to treat if statements with an init statement: `exclude` keeps them visible; `fold-body` hides the lines from `return` to the closing brace and keeps the header line visible.", Enum: []string{"exclude", "fold-body"}},
		{Name: "allow_bare_return", Type: "bool", Default: "false", Description: "Also hide a bare return."},
		{Name: "allow_calls_in_results", Type: "bool", Default: "false", Description: "Allow function calls in the results before the error; function literals and channel receives still do not match."},
	},
}

// NoopSettings holds the settings of the noop preset.
type NoopSettings struct {
	// Globs that limit the files this preset applies to, on top of
	// `files.include` and `files.exclude`.
	Paths []string `yaml:"paths"`

	// Globs of files this preset skips, on top of `files.exclude`.
	ExcludePaths []string `yaml:"exclude_paths"`

	// Hide the doc comment together with the function.
	IncludeDoc bool `yaml:"include_doc"`

	// Hide the method even when a comment other than the doc comment is on its
	// lines.
	AllowComments bool `yaml:"allow_comments"`

	// Also hide empty functions that are not methods, such as `func noop()
	// {}`.
	IncludeFunctions bool `yaml:"include_functions"`
}

// newNoopSettings returns a NoopSettings that holds the defaults.
func newNoopSettings() *NoopSettings {
	return &NoopSettings{IncludeDoc: true, AllowComments: true}
}

// decodeNoopSettings reads m, a value that passed the schema. A null or
// missing value keeps the default.
func decodeNoopSettings(m map[string]any) *NoopSettings {
	s := newNoopSettings()
	if v := m["paths"]; v != nil {
		s.Paths = stringsValue(v)
	}
	if v := m["exclude_paths"]; v != nil {
		s.ExcludePaths = stringsValue(v)
	}
	if v := m["include_doc"]; v != nil {
		s.IncludeDoc = boolValue(v)
	}
	if v := m["allow_comments"]; v != nil {
		s.AllowComments = boolValue(v)
	}
	if v := m["include_functions"]; v != nil {
		s.IncludeFunctions = boolValue(v)
	}
	return s
}

var noopSettingsSpec = settingsSpec{
	new:    func() any { return newNoopSettings() },
	decode: func(m map[string]any) any { return decodeNoopSettings(m) },
	infos: []SettingInfo{
		{Name: "paths", Type: "[]string", Default: "none", Description: "Globs that limit the files this preset applies to, on top of `files.include` and `files.exclude`."},
		{Name: "exclude_paths", Type: "[]string", Default: "none", Description: "Globs of files this preset skips, on top of `files.exclude`."},
		{Name: "include_doc", Type: "bool", Default: "true", Description: "Hide the doc comment together with the function."},
		{Name: "allow_comments", Type: "bool", Default: "true", Description: "Hide the method even when a comment other than the doc comment is on its lines."},
		{Name: "include_functions", Type: "bool", Default: "false", Description: "Also hide empty functions that are not methods, such as `func noop() {}`."},
	},
}

// schemaPresets maps the name of each preset in the schema to its
// settings.
var schemaPresets = map[string]settingsSpec{
	"getter": getterSettingsSpec,
	"iferr":  iferrSettingsSpec,
	"noop":   noopSettingsSpec,
}

// boolValue, intValue, stringValue, and stringsValue convert a value that
// passed the schema.
func boolValue(v any) bool {
	b, _ := v.(bool)
	return b
}

func intValue(v any) int {
	switch n := v.(type) {
	case int64:
		return int(n)
	case int:
		return n
	case float64:
		return int(n)
	}
	return 0
}

func stringValue(v any) string {
	s, _ := v.(string)
	return s
}

func stringsValue(v any) []string {
	l, _ := v.([]any)
	out := make([]string, 0, len(l))
	for _, item := range l {
		out = append(out, stringValue(item))
	}
	return out
}
