// Package gogen generates the Go types of a decoded configuration from
// the JSON Schema of the configuration, schema/gotebanare.schema.json.
//
// The schema is the source of truth. Generate writes two files:
//
//   - internal/config/config_gen.go: File, the top level of the
//     configuration, and the types of its sections.
//   - internal/presets/settings_gen.go: the settings struct of each preset
//     (definitions/<preset>Settings), its defaults, a decoder, and the
//     SettingInfo table that the documentation and the presets export
//     read.
//
// The decoders read values that already passed the schema, as
// internal/config produces them: map[string]any, []any, string, bool,
// int64, float64, and nil. A null or missing value keeps the default.
//
// The description of every preset setting must end with a sentence
// "Default: <text>.", which becomes SettingInfo.Default; the text before
// it becomes SettingInfo.Description. Every description must equal its
// markdownDescription.
package gogen

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"io"
	"regexp"
	"slices"
	"strings"

	"github.com/miyamo2/go-tebanare/schema"
)

// Files maps each generated file, relative to the repository root, to its
// content.
type Files map[string]string

const header = "// Code generated by dev/gogen from schema/gotebanare.schema.json; DO NOT EDIT.\n\n"

// Generate returns the generated files for the embedded schema.
func Generate() (Files, error) {
	return generate(schema.JSON)
}

func generate(src []byte) (Files, error) {
	root, err := parseObject(src)
	if err != nil {
		return nil, err
	}
	if err := checkDescriptions(root, "#"); err != nil {
		return nil, err
	}
	cfg, err := configFile(root)
	if err != nil {
		return nil, fmt.Errorf("config: %w", err)
	}
	set, err := settingsFile(root)
	if err != nil {
		return nil, fmt.Errorf("presets: %w", err)
	}
	return Files{
		"internal/config/config_gen.go":    cfg,
		"internal/presets/settings_gen.go": set,
	}, nil
}

// object is a JSON object that keeps the order of its keys.
type object struct {
	keys   []string
	values map[string]any
}

func (o *object) get(key string) any { return o.values[key] }

func (o *object) obj(key string) *object {
	v, _ := o.values[key].(*object)
	return v
}

func (o *object) str(key string) string {
	v, _ := o.values[key].(string)
	return v
}

// types returns the "type" of o without "null", and whether null is
// allowed.
func (o *object) types() (types []string, nullable bool) {
	switch t := o.get("type").(type) {
	case string:
		return []string{t}, false
	case []any:
		for _, v := range t {
			if s, _ := v.(string); s == "null" {
				nullable = true
			} else if s != "" {
				types = append(types, s)
			}
		}
	}
	return types, nullable
}

func parseObject(src []byte) (*object, error) {
	dec := json.NewDecoder(bytes.NewReader(src))
	dec.UseNumber()
	v, err := parseValue(dec)
	if err != nil {
		return nil, err
	}
	o, ok := v.(*object)
	if !ok {
		return nil, errors.New("the schema is not an object")
	}
	return o, nil
}

func parseValue(dec *json.Decoder) (any, error) {
	tok, err := dec.Token()
	if err != nil {
		return nil, err
	}
	switch tok {
	case json.Delim('{'):
		o := &object{values: map[string]any{}}
		for dec.More() {
			kt, err := dec.Token()
			if err != nil {
				return nil, err
			}
			k := kt.(string)
			v, err := parseValue(dec)
			if err != nil {
				return nil, err
			}
			o.keys = append(o.keys, k)
			o.values[k] = v
		}
		if _, err := dec.Token(); err != nil {
			return nil, err
		}
		return o, nil
	case json.Delim('['):
		var l []any
		for dec.More() {
			v, err := parseValue(dec)
			if err != nil {
				return nil, err
			}
			l = append(l, v)
		}
		if _, err := dec.Token(); err != nil && !errors.Is(err, io.EOF) {
			return nil, err
		}
		return l, nil
	}
	return tok, nil
}

// checkDescriptions checks that every description in the tree under v
// equals its markdownDescription.
func checkDescriptions(v any, at string) error {
	switch v := v.(type) {
	case *object:
		if d, md := v.get("description"), v.get("markdownDescription"); d != md {
			return fmt.Errorf("%s: description and markdownDescription differ", at)
		}
		for _, k := range v.keys {
			if err := checkDescriptions(v.values[k], at+"/"+k); err != nil {
				return err
			}
		}
	case []any:
		for i, item := range v {
			if err := checkDescriptions(item, fmt.Sprintf("%s/%d", at, i)); err != nil {
				return err
			}
		}
	}
	return nil
}

// field is one property of a generated struct.
type field struct {
	name    string // the property name
	goName  string
	goType  string
	decode  string // statement that assigns v to s.<goName>
	init    string // the default as a Go expression, or ""
	doc     string
	setting settingInfo
}

// settingInfo is the SettingInfo of a preset setting.
type settingInfo struct {
	typ, def, desc string
	enum           []string
}

// structType is a generated struct with its new and decode functions.
type structType struct {
	name   string
	doc    string
	fields []field
}

// fieldsOf returns the fields of the object schema s. Inline object
// properties become their own structs, appended to nested.
func fieldsOf(s *object, owner string, nested *[]structType) ([]field, error) {
	props := s.obj("properties")
	if props == nil {
		return nil, fmt.Errorf("%s: no properties", owner)
	}
	required := map[string]bool{}
	if req, ok := s.get("required").([]any); ok {
		for _, r := range req {
			required[r.(string)] = true
		}
	}
	var out []field
	for _, name := range props.keys {
		p := props.obj(name)
		f := field{name: name, goName: goName(name), doc: p.str("description")}
		types, _ := p.types()
		typ := ""
		if len(types) == 1 {
			typ = types[0]
		}
		def := p.get("default")
		switch typ {
		case "boolean":
			f.goType, f.decode = "bool", "s.%s = boolValue(v)"
			f.setting.typ = "bool"
			if def != nil {
				if b, ok := def.(bool); !ok {
					return nil, fmt.Errorf("%s.%s: default %v is not a boolean", owner, name, def)
				} else if b {
					f.init = "true"
				}
			}
		case "integer":
			f.setting.typ = "int"
			switch {
			case def != nil:
				n, ok := def.(json.Number)
				if _, err := n.Int64(); !ok || err != nil {
					return nil, fmt.Errorf("%s.%s: default %v is not an integer", owner, name, def)
				}
				f.goType, f.decode, f.init = "int", "s.%s = intValue(v)", n.String()
			case required[name]:
				f.goType, f.decode = "int", "s.%s = intValue(v)"
			default:
				f.goType, f.decode = "*int", "n := intValue(v)\ns.%s = &n"
			}
		case "string":
			f.goType, f.decode = "string", "s.%s = stringValue(v)"
			f.setting.typ = "string"
			if def != nil {
				d, ok := def.(string)
				if !ok {
					return nil, fmt.Errorf("%s.%s: default %v is not a string", owner, name, def)
				}
				f.init = fmt.Sprintf("%q", d)
			}
			if enum, ok := p.get("enum").([]any); ok {
				for _, e := range enum {
					if e, ok := e.(string); ok {
						f.setting.enum = append(f.setting.enum, e)
					}
				}
			}
		case "array":
			items := p.obj("items")
			if items != nil && items.str("type") == "string" {
				f.goType, f.decode = "[]string", "s.%s = stringsValue(v)"
				f.setting.typ = "[]string"
				if def != nil {
					l, ok := def.([]any)
					if !ok {
						return nil, fmt.Errorf("%s.%s: default %v is not a list", owner, name, def)
					}
					var elems []string
					for _, e := range l {
						s, ok := e.(string)
						if !ok {
							return nil, fmt.Errorf("%s.%s: default %v is not a list of strings", owner, name, def)
						}
						elems = append(elems, fmt.Sprintf("%q", s))
					}
					f.init = "[]string{" + strings.Join(elems, ", ") + "}"
				}
			} else {
				f.goType, f.decode = "[]any", "s.%s = v.([]any)"
			}
		case "object":
			sub := owner + goName(name)
			if owner == "File" {
				sub = goName(name)
			}
			subFields, err := fieldsOf(p, sub, nested)
			if err != nil {
				return nil, err
			}
			doc := fmt.Sprintf("%s is the value of `%s`. %s", sub, name, p.str("description"))
			*nested = append(*nested, structType{name: sub, doc: doc, fields: subFields})
			f.goType = "*" + sub
			f.decode = "s.%s = decode" + sub + "(v.(map[string]any))"
		default:
			return nil, fmt.Errorf("%s.%s: unsupported type %v", owner, name, p.get("type"))
		}
		out = append(out, f)
	}
	return out, nil
}

// configFile generates internal/config/config_gen.go.
func configFile(root *object) (string, error) {
	var nested []structType
	fields, err := fieldsOf(root, "File", &nested)
	if err != nil {
		return "", err
	}
	doc := "File is a decoded configuration. " + root.str("description")
	types := append([]structType{{name: "File", doc: doc, fields: fields}}, nested...)
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("package config\n\n")
	for _, t := range types {
		writeStruct(&b, t)
	}
	writeValueHelpers(&b)
	return formatSource(b.String())
}

// defaultSentence splits a setting description into its text and the
// default.
var defaultSentence = regexp.MustCompile(`^(.*) Default: (.+)\.$`)

// settingsFile generates internal/presets/settings_gen.go.
func settingsFile(root *object) (string, error) {
	names, err := presetNames(root)
	if err != nil {
		return "", err
	}
	defs := root.obj("definitions")
	if defs == nil {
		return "", errors.New("no definitions")
	}
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("package presets\n\n")
	for _, name := range names {
		def := defs.obj(name + "Settings")
		if def == nil {
			return "", fmt.Errorf("no definitions/%sSettings for preset %s", name, name)
		}
		typeName := goName(name) + "Settings"
		var nested []structType
		fields, err := fieldsOf(def, typeName, &nested)
		if err != nil {
			return "", err
		}
		if len(nested) > 0 {
			return "", fmt.Errorf("%s: nested objects are not supported in settings", typeName)
		}
		for i := range fields {
			f := &fields[i]
			m := defaultSentence.FindStringSubmatch(f.doc)
			if m == nil {
				return "", fmt.Errorf("%s.%s: the description does not end with \"Default: <text>.\"", typeName, f.name)
			}
			f.setting.desc, f.setting.def = m[1], m[2]
			f.doc = m[1]
		}
		writeStruct(&b, structType{
			name:   typeName,
			doc:    fmt.Sprintf("%s holds the settings of the %s preset.", typeName, name),
			fields: fields,
		})
		fmt.Fprintf(&b, "var %sSettingsSpec = settingsSpec{\n", name)
		fmt.Fprintf(&b, "\tnew:    func() any { return new%s() },\n", typeName)
		fmt.Fprintf(&b, "\tdecode: func(m map[string]any) any { return decode%s(m) },\n", typeName)
		b.WriteString("\tinfos: []SettingInfo{\n")
		for _, f := range fields {
			fmt.Fprintf(&b, "\t\t{Name: %q, Type: %q, Default: %q, Description: %q", f.name, f.setting.typ, f.setting.def, f.setting.desc)
			if len(f.setting.enum) > 0 {
				fmt.Fprintf(&b, ", Enum: %#v", f.setting.enum)
			}
			b.WriteString("},\n")
		}
		b.WriteString("\t},\n}\n\n")
	}
	b.WriteString("// schemaPresets maps the name of each preset in the schema to its\n// settings.\n")
	b.WriteString("var schemaPresets = map[string]settingsSpec{\n")
	for _, name := range names {
		fmt.Fprintf(&b, "\t%q: %sSettingsSpec,\n", name, name)
	}
	b.WriteString("}\n\n")
	writeValueHelpers(&b)
	return formatSource(b.String())
}

// presetNames returns the preset names that the schema lists as the enum
// of a preset name in `presets`, sorted.
func presetNames(root *object) ([]string, error) {
	items := root.obj("properties").obj("presets").obj("items")
	if items == nil {
		return nil, errors.New("no properties/presets/items")
	}
	anyOf, _ := items.get("anyOf").([]any)
	for _, alt := range anyOf {
		if o, ok := alt.(*object); ok && o.str("type") == "string" {
			var names []string
			enum, _ := o.get("enum").([]any)
			for _, e := range enum {
				names = append(names, e.(string))
			}
			slices.Sort(names)
			return names, nil
		}
	}
	return nil, errors.New("properties/presets/items has no string alternative with the preset names")
}

func writeStruct(b *strings.Builder, t structType) {
	writeComment(b, "", t.doc)
	fmt.Fprintf(b, "type %s struct {\n", t.name)
	for i, f := range t.fields {
		if i > 0 {
			b.WriteString("\n")
		}
		writeComment(b, "\t", f.doc)
		fmt.Fprintf(b, "\t%s %s `yaml:%q`\n", f.goName, f.goType, f.name)
	}
	b.WriteString("}\n\n")

	fmt.Fprintf(b, "// new%s returns a %s that holds the defaults.\n", t.name, t.name)
	fmt.Fprintf(b, "func new%s() *%s {\n\treturn &%s{", t.name, t.name, t.name)
	var inits []string
	for _, f := range t.fields {
		if f.init != "" {
			inits = append(inits, fmt.Sprintf("%s: %s", f.goName, f.init))
		}
	}
	b.WriteString(strings.Join(inits, ", "))
	b.WriteString("}\n}\n\n")

	fmt.Fprintf(b, "// decode%s reads m, a value that passed the schema. A null or\n// missing value keeps the default.\n", t.name)
	fmt.Fprintf(b, "func decode%s(m map[string]any) *%s {\n\ts := new%s()\n", t.name, t.name, t.name)
	for _, f := range t.fields {
		fmt.Fprintf(b, "\tif v := m[%q]; v != nil {\n\t\t%s\n\t}\n", f.name, fmt.Sprintf(f.decode, f.goName))
	}
	b.WriteString("\treturn s\n}\n\n")
}

// writeComment writes text as a Go comment wrapped at about 76 columns.
func writeComment(b *strings.Builder, indent, text string) {
	if text == "" {
		return
	}
	line := ""
	for _, w := range strings.Fields(text) {
		if line != "" && len(indent)+3+len(line)+1+len(w) > 76 {
			fmt.Fprintf(b, "%s// %s\n", indent, line)
			line = ""
		}
		if line != "" {
			line += " "
		}
		line += w
	}
	fmt.Fprintf(b, "%s// %s\n", indent, line)
}

func writeValueHelpers(b *strings.Builder) {
	b.WriteString(`// boolValue, intValue, stringValue, and stringsValue convert a value that
// passed the schema.
func boolValue(v any) bool {
	b, _ := v.(bool)
	return b
}

func intValue(v any) int {
	switch n := v.(type) {
	case int64:
		return int(n)
	case int:
		return n
	case float64:
		return int(n)
	}
	return 0
}

func stringValue(v any) string {
	s, _ := v.(string)
	return s
}

func stringsValue(v any) []string {
	l, _ := v.([]any)
	out := make([]string, 0, len(l))
	for _, item := range l {
		out = append(out, stringValue(item))
	}
	return out
}
`)
}

// goName turns a snake_case property name into an exported Go name.
func goName(name string) string {
	var b strings.Builder
	for _, part := range strings.Split(name, "_") {
		if part != "" {
			b.WriteString(strings.ToUpper(part[:1]) + part[1:])
		}
	}
	return b.String()
}

func formatSource(src string) (string, error) {
	out, err := format.Source([]byte(src))
	if err != nil {
		return "", fmt.Errorf("format: %w\n%s", err, src)
	}
	return string(out), nil
}
