package config

import (
	"errors"
	"os"
	"slices"
	"strings"
	"testing"

	"github.com/miyamo2/go-tebanare/internal/nodematch"
	"github.com/miyamo2/go-tebanare/internal/result"
	"github.com/miyamo2/go-tebanare/internal/rule"
)

func readFile(tb testing.TB, name string) []byte {
	tb.Helper()
	src, err := os.ReadFile(name)
	if err != nil {
		tb.Fatal(err)
	}
	return src
}

// compileError compiles src and returns the diagnostics of the *Error.
func compileError(t *testing.T, src string) []result.Diagnostic {
	t.Helper()
	set, _, err := Compile([]byte(src))
	var ce *Error
	if !errors.As(err, &ce) || set != nil {
		t.Fatalf("Compile(%q) = %v, %v; want an *Error", src, set, err)
	}
	return ce.Diagnostics
}

type ruleSummary struct {
	ID, Description, Preset string
	Target                  result.Target
	IncludeDoc              bool
	Paths                   string
}

func summarize(rules []*rule.Rule) []ruleSummary {
	out := make([]ruleSummary, len(rules))
	for i, r := range rules {
		out[i] = ruleSummary{r.ID, r.Description, r.Preset, r.Target, r.IncludeDoc, strings.Join(r.Paths, ",")}
	}
	return out
}

func TestCompileExample(t *testing.T) {
	set, warns, err := Compile(readFile(t, "testdata/example.yml"))
	if err != nil || len(warns) > 0 {
		t.Fatalf("Compile = %v, warnings %q", err, format(warns))
	}
	if !slices.Equal(set.Include, []string{"**/*.go"}) || !slices.Equal(set.Exclude, []string{"vendor/**", "third_party/**"}) {
		t.Errorf("Include = %q, Exclude = %q", set.Include, set.Exclude)
	}
	want := []ruleSummary{
		{"stringer", "Skip fmt.Stringer implementations", "", result.TargetFunc, true, ""},
		{"gomock", "Mocks generated by gomock", "", result.TargetFunc, true, "**/mock_*.go"},
		{"generic-repo-finders", "", "", result.TargetFunc, true, ""},
		{"must", "", "", result.TargetFunc, true, ""},
		{"tracing", "", "", result.TargetStmt, false, ""},
		{"debug-log", "", "", result.TargetExpr, false, ""},
		{"getter", "", "getter", result.TargetFunc, true, ""},
		{"noop", "", "noop", result.TargetFunc, true, ""},
		{"iferr", "", "iferr", result.TargetStmt, false, ""},
	}
	got := summarize(set.Rules)
	for i := range got {
		if got[i].Preset != "" {
			got[i].Description = "" // preset summaries belong to package presets
		}
	}
	if !slices.Equal(got, want) {
		t.Fatalf("rules =\n%+v\nwant\n%+v", got, want)
	}

	decls := funcDecls(t, `
func (r *Repository[T]) FindAll(ctx context.Context) ([]T, error) { return nil, nil }
func (r Repository[T]) FindOne(ctx context.Context) (T, error) { var v T; return v, nil }
func Must[V any](v V, err error) V { return v }
`)
	byID := map[string]*rule.Rule{}
	for _, r := range set.Rules {
		byID[r.ID] = r
	}
	for _, tc := range []struct {
		id, fn string
		want   bool
	}{
		{"generic-repo-finders", "FindAll", true},
		{"generic-repo-finders", "FindOne", false},
		{"must", "Must", true},
		{"stringer", "Must", false},
	} {
		if got := byID[tc.id].Func.MatchFunc(decls[tc.fn], nil); got != tc.want {
			t.Errorf("%s matches %s = %v, want %v", tc.id, tc.fn, got, tc.want)
		}
	}
	if !byID["tracing"].Node.(*nodematch.Matcher).MatchText(`ctx, span := otel.Start(ctx, "x")`) {
		t.Error("tracing does not match its example")
	}
	debug := byID["debug-log"]
	if m := debug.Node.(*nodematch.Matcher); !m.MatchText(`log.Debugf("id=%d", id)`) || m.MatchText(`log.Debug("password", p)`) {
		t.Error("debug-log does not follow regex and not_regex")
	}
	if debug.Hide != rule.HideSelf || debug.IncludeLeadingComments {
		t.Errorf("debug-log = %+v", debug)
	}
	s, f := firstIf(t, "if parseErr != nil { return parseErr }")
	if _, ok := byID["iferr"].Node.MatchNode(s, f); !ok {
		t.Error("iferr does not use names [err, *Err]")
	}
}

func TestCompileMinimal(t *testing.T) {
	set, warns, err := Compile(readFile(t, "testdata/minimal.yml"))
	if err != nil || len(warns) > 0 {
		t.Fatalf("Compile = %v, warnings %q", err, format(warns))
	}
	want := []ruleSummary{
		{"getter", "", "getter", result.TargetFunc, true, ""},
		{"noop", "", "noop", result.TargetFunc, true, ""},
		{"iferr", "", "iferr", result.TargetStmt, false, ""},
	}
	got := summarize(set.Rules)
	for i := range got {
		got[i].Description = ""
	}
	if !slices.Equal(got, want) || set.Include != nil || set.Exclude != nil {
		t.Errorf("set = %+v, rules %+v", set, got)
	}
	if !set.IsTarget("internal/x.go") {
		t.Error("the default include does not apply")
	}
}

func TestCompileFiles(t *testing.T) {
	src := "version: 1\nfiles:\n  include: [\"**/*.go\"]\n  exclude: [\"vendor/**\", \"third_party/**\"]\npresets: [iferr]\n"
	set, warns, err := Compile([]byte(src))
	if err != nil || len(warns) > 0 {
		t.Fatalf("Compile = %v, warnings %q", err, format(warns))
	}
	if !slices.Equal(set.Include, []string{"**/*.go"}) || !slices.Equal(set.Exclude, []string{"vendor/**", "third_party/**"}) {
		t.Errorf("Include = %q, Exclude = %q", set.Include, set.Exclude)
	}
	if !set.IsTarget("internal/x.go") || set.IsTarget("vendor/x/x.go") {
		t.Error("files.exclude does not apply")
	}
}

// exampleWith returns the example config with old replaced by new.
func exampleWith(t *testing.T, old, new string) string {
	t.Helper()
	src := string(readFile(t, "testdata/example.yml"))
	if !strings.Contains(src, old) {
		t.Fatalf("example does not contain %q", old)
	}
	return strings.Replace(src, old, new, 1)
}

func TestCompilePlanErrorExamples(t *testing.T) {
	ds := compileError(t, exampleWith(t, "Find*(context.Context, ...)", "Find*(, ...)"))
	want := ".gotebanare.yml:26:11: rules[2](generic-repo-finders).func: 1:29: expected type, found ','\n" +
		"    func (*Repository[_]) Find*(, ...) (_, error)\n" +
		"                                ^"
	if len(ds) != 1 || ds[0].Format(".gotebanare.yml") != want {
		t.Errorf("diagnostics = %q\nwant %q", format(ds), want)
	}

	ds = compileError(t, exampleWith(t, `\.Start\(ctx, .+\)$`, `\.Start\(ctx, (.+\)$`))
	prefix := ".gotebanare.yml:36:11: rules[4](tracing).stmt.regex[0]: error parsing regexp: missing closing ): "
	if len(ds) != 1 || !strings.HasPrefix(ds[0].Format(".gotebanare.yml"), prefix) {
		t.Errorf("diagnostics = %q\nwant prefix %q", format(ds), prefix)
	}
	if d := ds[0]; d.Severity != result.SeverityError || d.Code != result.CodeConfigInvalid || d.RuleID != "tracing" {
		t.Errorf("diagnostic = %+v", d)
	}
}

func TestCompileErrors(t *testing.T) {
	tests := []struct {
		name string
		src  string
		want []string
	}{
		{"not a mapping", "- version: 1", []string{"1:1: expected a mapping, found a list"}},
		{"missing version", "\npresets: []", []string{`2:1: missing required key "version"`}},
		{"unknown version", "version: 2", []string{"1:10: version: unsupported version 2 (supported versions: 1)"}},
		{"version as a string", "version: '1'", []string{`1:10: version: expected an integer, found string "1"`}},
		{"unknown key", "version: 1\nrule: []", []string{
			`2:1: rule: unknown key "rule" (allowed keys: version, files, presets, rules)`,
		}},
		{"files", "version: 1\nfiles:\n  include: ['[']\n  exclude: '**'\n  excludes: []", []string{
			`3:13: files.include[0]: invalid glob "["`,
			`4:12: files.exclude: expected a list of strings, found string "**"`,
			`5:3: files.excludes: unknown key "excludes" (allowed keys: include, exclude)`,
		}},
		{"files not a mapping", "version: 1\nfiles: ['**']", []string{"2:8: files: expected a mapping, found a list"}},
		{"rule id equal to an enabled preset", "version: 1\nrules:\n  - id: iferr\n    func: 'func A()'\npresets: [iferr]", []string{
			`3:9: rules[0](iferr).id: id "iferr" is the name of the preset enabled on line 5`,
		}},
		// The alias check runs first and stops the compiler, so the
		// version and the unknown key are not reported.
		{"aliases past the limit", "version: 3\na: &a " + strings.Repeat("x", maxAliasCopy) + "\npresets: [*a]", []string{
			"3:11: " + tooMuch,
		}},
		{"alias inside its value", "version: 1\npresets: &a [*a]", []string{"2:14: alias *a refers to a value that contains it"}},
		// files is checked before presets; the errors come back sorted.
		{"errors in several sections, sorted", "version: 3\npresets: [x]\nfiles: {include: 1}", []string{
			"1:10: version: unsupported version 3 (supported versions: 1)",
			`2:11: presets[0](x): unknown preset "x" (available presets: getter, iferr, noop)`,
			"3:18: files.include: expected a list of strings, found integer 1",
		}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ds := compileError(t, tt.src)
			checkDiags(t, "errors", ds, tt.want)
			for _, d := range ds {
				if d.Severity != result.SeverityError || d.Code != result.CodeConfigInvalid {
					t.Errorf("%s: severity %s, code %s", d.Format(""), d.Severity, d.Code)
				}
			}
		})
	}
}

func TestCompileWarnings(t *testing.T) {
	src := "version: 1\nrules:\n  - id: a\n    stmt: {regex: [x, '^y']}\n  - id: b\n    func: 'func /Get/()'\n"
	set, warns, err := Compile([]byte(src))
	if err != nil || set == nil {
		t.Fatalf("Compile: %v", err)
	}
	checkDiags(t, "warnings", warns, []string{
		`4:20: rules[0](a).stmt.regex[0]: regex "x" is not anchored with ^ or $, so it can match any part of the normalized text`,
		"6:11: rules[1](b).func: name regexp /Get/ is not anchored with ^ or $, so it matches every name that contains a match",
	})
	for _, d := range warns {
		if d.Severity != result.SeverityWarning || d.Code != result.CodeUnanchoredRegexp {
			t.Errorf("%s: severity %s, code %s", d.Format(""), d.Severity, d.Code)
		}
	}

	// Warnings come back with the error of an invalid config.
	_, warns, err = Compile([]byte(src + "  - id: a\n    func: 'func B()'\n"))
	if err == nil || len(warns) != 2 {
		t.Errorf("Compile = %v, warnings %q", err, format(warns))
	}
}

func TestErrorString(t *testing.T) {
	err := &Error{Diagnostics: []result.Diagnostic{
		{Line: 1, Column: 10, Field: "version", Message: "unsupported version 2"},
		{Line: 3, Column: 5, Field: "presets[0]", Message: "a\n  b"},
	}}
	if got, want := err.Error(), "1:10: version: unsupported version 2\n3:5: presets[0]: a\n  b"; got != want {
		t.Errorf("Error() = %q, want %q", got, want)
	}
	if got := (&Error{}).Error(); got != "invalid configuration" {
		t.Errorf("empty Error() = %q", got)
	}
}
