// Code generated by dev/gogen from schema/gotebanare.schema.json; DO NOT EDIT.

package config

// File is a decoded configuration. Configuration of go-tebanare, read from
// `.gotebanare.yml` or `.gotebanare.yaml` at the repository root. See
// https://github.com/miyamo2/go-tebanare/blob/main/docs/configuration.md.
type File struct {
	// Version of the configuration format. Must be `1`.
	Version int `yaml:"version"`

	// The files to analyze.
	Files *Files `yaml:"files"`

	// Built-in presets to enable. Listing a preset twice is an error.
	Presets []any `yaml:"presets"`
}

// newFile returns a File that holds the defaults.
func newFile() *File {
	return &File{}
}

// decodeFile reads m, a value that passed the schema. A null or
// missing value keeps the default.
func decodeFile(m map[string]any) *File {
	s := newFile()
	if v := m["version"]; v != nil {
		s.Version = intValue(v)
	}
	if v := m["files"]; v != nil {
		s.Files = decodeFiles(v.(map[string]any))
	}
	if v := m["presets"]; v != nil {
		s.Presets = v.([]any)
	}
	return s
}

// Files is the value of `files`. The files to analyze.
type Files struct {
	// Files to analyze, as doublestar globs relative to the repository root.
	// The default, also used for an empty list, is `["**/*.go"]`.
	Include []string `yaml:"include"`

	// Files to skip even when `include` matches them.
	Exclude []string `yaml:"exclude"`
}

// newFiles returns a Files that holds the defaults.
func newFiles() *Files {
	return &Files{}
}

// decodeFiles reads m, a value that passed the schema. A null or
// missing value keeps the default.
func decodeFiles(m map[string]any) *Files {
	s := newFiles()
	if v := m["include"]; v != nil {
		s.Include = stringsValue(v)
	}
	if v := m["exclude"]; v != nil {
		s.Exclude = stringsValue(v)
	}
	return s
}

// boolValue, intValue, stringValue, and stringsValue convert a value that
// passed the schema.
func boolValue(v any) bool {
	b, _ := v.(bool)
	return b
}

func intValue(v any) int {
	switch n := v.(type) {
	case int64:
		return int(n)
	case int:
		return n
	case float64:
		return int(n)
	}
	return 0
}

func stringValue(v any) string {
	s, _ := v.(string)
	return s
}

func stringsValue(v any) []string {
	l, _ := v.([]any)
	out := make([]string, 0, len(l))
	for _, item := range l {
		out = append(out, stringValue(item))
	}
	return out
}
